server:
  port: 8082

spring:
  #  profiles:
  #    active: prod
  datasource:
    #    hikari:
    #      max-lifetime: 170000 # 170초
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: true

logging.level:
  org.hibernate.SQL: debug
#org.hibernate.type: trace
#로그 파일을 남김.